---
name: Build Executable

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.10.11 # Substitua pela versão do Python que você usa

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip freeze
                  pip install cx_freeze

            - name: Build executable
              run: python build_w10.py build

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: smartflux
                  path: build/exe.win-amd64-3.10
